### ISSUE TITLE
Optimization Plans for Conv2D CPU Execution

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#1130]
Hello, I wonder if there are any future plans to optimize Conv2D CPU execution. I guess currently MLX uses a naive implementation?

**Comment by awni** [comment]
We don't have an immediate plan for this. I'm sure there is potential to make CPU convolutions faster. I'm curious though, why not use the GPU instead?

**Comment by briancpark** [comment]
Has there been an attempt or discussion to port in BNNS conv into MLX? [It's listed as TODO](https://github.com/ml-explore/mlx/blob/e6fecbb3e1e2ecb51247280f3738d670241777db/mlx/backend/accelerate/conv.cpp#L17).
I've looked into it personally, but I'm noticing some limitations with BNNS API and MLX. For one, different format preferences. I believe BNNS prefers NCHW and OIHW, instead of NHWC and OHWI in MLX. I assume the latter is chosen as implementing the Metal variant was priority, and it has better performance properties under those formats in GPU-land.

For me, the answer for why not use GPU instead is that CPU could be more efficient. I've seen some cases in CoreML where CNNs compiled under GPU only perform as same or marginally better than CNNs compiled on CPU-only. And it could be the case the CPU is more energy efficient? (I never confirmed).

**Comment by awni** [comment]
I don't think we've benchmarked the convs in BNNS but it would be interesting to see how they perform. There would have to be a copy in and out as everything in MLX assumes channels are last so that might hinder perf.

Regarding efficiency, the CPU will likely be faster (with a good implementation) for smaller models, the GPU for larger models. As for power efficiency, I do not know how they stack up and how it changes with scale.. a very good question.

**Comment by mlaves** [comment]
I also noticed the slowness of `conv` on the CPU when I implemented conv3d in #993. I looked into it and the operation on the cpu could be substantially faster when using [explicit_gemm_conv_ND_cpu](https://github.com/ml-explore/mlx/blob/7cca1727af6deb61654846c0332abe783bdb2aff/mlx/backend/common/conv.cpp#L907) instead of the naive implementation. However, for `conv2d` and `conv3d`, using `explicit_gemm_conv_ND_cpu` was slower in total, because the necessary reshaping of the inputs ([happening here](https://github.com/ml-explore/mlx/blob/7cca1727af6deb61654846c0332abe783bdb2aff/mlx/backend/common/conv.cpp#L990)) is very slow.
PyTorch's `conv` cpu implementation is 10x faster on my M2 Pro, and they [also use gemm-conv](https://github.com/pytorch/pytorch/blob/b23b6e7108b8173f9e03805704c8ea0c1e8a2ea5/aten/src/ATen/native/ConvolutionMM3d.cpp#L300).
