### ISSUE TITLE
[BUG] compile + checkpoint segfaults

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx#1162]
```python
import mlx.core as mx
import mlx.nn as nn
from mlx.nn.utils import checkpoint

dims = 32

class Linear(nn.Module):
    def __init__(self, dims):
        super().__init__()
        self.proj = nn.Linear(dims, dims)

    def __call__(self, x):
        l = checkpoint(self.proj) 
        x = l(x)
        return x

model = Linear(dims)
mx.eval(model.parameters())

@mx.compile
def step(inputs):
    return model(inputs)

inputs = mx.ones((2, dims), dtype=mx.float32)
mx.eval(inputs)

out = step(inputs)
mx.eval(out)
```

Above segfaults with checkpointing but not without.

**Comment by angeloskath** [comment]
All right so far this seems to be that the compiler cache is destroyed after the Python interpreter has been destroyed and when deleting the python closure the first thing that is attempted is to get the GIL of course which is not possible since there is no interpreter available.

Will look into it more but it shouldn't be too hard to fix.
