### ISSUE TITLE
[Feature] Add nan_to_num Function

### ISSUE THREAD

**Issue by abdussamettrkr** [ml-explore/mlx#1187]
Hello, In libraries such as Numpy, Jax, and Torch, we use a nan_to_num function to handle non-numeric values like NaNs and infinities. This function is currently not implemented in the MLX library. I believe adding this function would be useful.

**Comment by awni** [comment]
For now, you can do this with where (maybe a couple of where's depending on how you want to handle inf).

```python
mx.where(mx.isnan(x), val, x)
```

**Comment by abdussamettrkr** [comment]
Sorry, I meant to  'nan_to_num'. Thanks, I will use the 'where' function for now.

**Comment by Commit2Cosmos** [comment]
Hi @awni, can I take it as my first contribution please? I have coded it up, but quite unsure about what the types of `nan`, `posinf` and `neginf` should be (right now it I've set it to `ScalarOrArray` and it seems to work; using `float` or `double` fails tests, because `to_array` converts them to `complex64`). I understand their types should be related to that of the input array, but cannot quite figure out how. I'll make a DPL for you to look at. Also, please let me know of any other tests you'd like to see.

**Comment by awni** [comment]
I left comments in the code about this.
