### ISSUE TITLE
[Question] is there parallel processing for cpu?

### ISSUE THREAD

**Issue by sooyoung-wind** [ml-explore/mlx#1218]
I'm interested in MLX even if I don't have a Mac. I'm using MLX on Colab. So I an trying to run examples in the cpu. I wonder if I can set up multicores if there are multiple cpu cores. If anyone knows this, please let me know.
Thanks. :)

**Comment by awni** [comment]
You have two options to use parallelism in MLX right now:
1. With [streams](https://ml-explore.github.io/mlx/build/html/usage/using_streams.html). Streams are kind of like threads in their overhead (each stream spawns a thread). You can control which operations run on a given stream by passing the stream to the operation or using a context manager for a block of operations.
2. You can use multiprocessing with MPI and [`mlx.core.distributed`](https://ml-explore.github.io/mlx/build/html/usage/distributed.html). This is higher level parallelism for e.g. data parallel training or something.

At some point we intend to add more fine-grained parallelism in our CPU back-end so that individual operations can run faster on multi-core machines. However, that is probably a ways out from now since the CPU back-end is lower priority at the moment.

I'm also curious to know why you are using MLX in Colab vs a framework which is more designed for Nvidia GPUs like PyTorch or Jax?

(Closing this issue for now as I don't think there is anything actionable to do here at the moment).
