### ISSUE TITLE
MLX Evaluation / Roadmap?

### ISSUE THREAD

**Issue by jrp2014** [ml-explore/mlx#1411]
My understanding is that MLX was invented to take advantage of the unified cpu-gpu architecture of the Apple Silicon chips in ways that PyTorch et al / MTS didn't (notably avoiding copying).  It is also open source, and so stands apart from the MacOS AI Frameworks.

A good deal of the focus seems to be on providing the infrastructure for building / training new AI models although it is perfectly possible to run them, as mlx-examples shows, although presumably that doesn't use quite as much of the mlx infrastructure as building and training.

Just as we are on the eve of the launch of a new MacOS, can I ask what are the evaluation plans for the MLX approach?  It can certainly perform faster than PyTorch on some tasks?  And llama.cpp?

If the benchmarks can show speed and memory (model size) benefits, there are costs in having to convert / adapt hugging face models, which might have more impact on some workflows.

Anyway, now the library is maturing, what are the plans for evaluating it and, perhaps and, perhaps, putting together a bit more of a roadmap based on the evaluation?

**Comment by ashran** [comment]
I generally agree. A clear roadmap would make people have more confidence in MLX and port/develop their projects.

**Comment by thegodone** [comment]
Lot of models type cannot be validated due to missing or in development of equivalent functions (like scatter for Graphs), Should we also need to include list of missing equivalent functions in the roadmap to avoid devs to lose time for searching if what they need is already there ?

**Comment by awni** [comment]
> Can I ask what are the evaluation plans for the MLX approach? It can certainly perform faster than PyTorch on some tasks? And llama.cpp?

For the most part we don't intend to publish direct benchmarks comparing different frameworks. We'll provide examples and MLX benchmarks that you can run. But will look to more independent sources to benchmark e.g. MLX vs Llama.cpp or PyTorch. So you can certainly measure tokens-per-second using [MLX LM](https://pypi.org/project/mlx-lm/) for many different models, or image generation time with say [FLUX + DiffusionKit](https://github.com/argmaxinc/DiffusionKit), or [Transformer training time with our example](https://github.com/ml-explore/mlx-examples/tree/main/transformer_lm) and then compare those to other frameworks as you like. We welcome the benchmarks if you publish them here or elsewhere.

> Putting together a bit more of a roadmap

Not opposed to putting together a roadmap as a public artifact. But in the meantime if you have specific questions about whether or not we intend to work on something you can always ask in GH discussion.

> Should we also need to include list of missing equivalent functions in the roadmap to avoid devs to lose time for searching if what they need is already there ?

@thegodone Please file an issue for any missing functions that you encounter. That would be super useful! For most common functions (e.g. ones you find in NumPy or the [Python Array API](https://data-apis.org/array-api/latest/), we intend to add them. In some cases we don't but the issue is still useful to discuss why and/or if we should reconsider. GH issues is the best place  for us to track missing features.

**Comment by jrp2014** [comment]
Thanks. The ad hoc approach to evaluation is fine, but does not really help me understand the tradeoffs between the potentially better speed / size performance versus cost of needing to use a similar but different interface, the need to convert models and the smaller ecosystem, etc.  I'd have thought that some more systematic evaluation might also help to guide the focus of future effort.  But it's good to understand your stance. Thanks again.
