### ISSUE TITLE
can mlx work with stable-diffusion-webui ?

### ISSUE THREAD

**Issue by bobz965** [ml-explore/mlx#151]
can mlx work with stable-diffusion-webui ? 
are there some docs about this ?

thanks for your reply.

**Comment by angeloskath** [comment]
Not out of the box as that is written for PyTorch but it should be fairly easy to port the gradio demo and utilize the stable diffusion example. If it is fairly self-contained we would love a PR in the `mlx-examples` repository.

I will close this issue here, feel free to open one in the examples repo or make a PR there.
