### ISSUE TITLE
[BUG] really bizarre behavior from vmap

### ISSUE THREAD

**Issue by feitreim** [ml-explore/mlx#1599]
Here's a formatted GitHub issue report:

**Describe the bug**
MLX's `vmap` throws errors about concatenation for a simple function that takes a 3-vector and turns it into a diagonal matrix, but then for code that should produce exactly the same output, with some additional weird work, it works.

**To Reproduce**
```python
import mlx.core as mx

def get_scale_fails(s: mx.array) -> mx.array:
    # This fails with vmap
    return mx.array([s[0], 0.0, 0.0, 0.0, s[1], 0.0, 0.0, 0.0, s[2]]).reshape(3, 3)

def get_scale_works(s: mx.array) -> mx.array:
    # This works with vmap
    return mx.array([
        s[0] * 1.0, s[0] * 0.0, s[0] * 0.0,
        s[1] * 0.0, s[1] * 1.0, s[1] * 0.0,
        s[2] * 0.0, s[2] * 0.0, s[2] * 1.0
    ]).reshape(3, 3)

# Test data
s = mx.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# This fails
try:
    result = mx.vmap(get_scale_fails)(s)
except ValueError as e:
    print("Error:", e)
    # Outputs: ValueError: [concatenate] All the input arrays must have the same number of dimensions. However, got arrays with dimensions 2 and 1.

# This works
result = mx.vmap(get_scale_works)(s)
print("Success shape:", result.shape)
# Outputs: (2, 3, 3)
```

**Expected behavior**
Both functions should work with `vmap` since they are logically equivalent - they both create a 3x3 matrix with the input vector on the diagonal. The only difference is that one uses direct indexing while the other uses arithmetic operations.

**Desktop (please complete the following information):**
 - OS: MacOS 15.2
 - MLX Version: 0.20.0

**Additional context**
I was just incredibly confused by this bug, I asked sonnet 3.5 for some help and it still took a while to figure out to get something working. But here is claudes thoughts

LLM OUTPUT:
***
This seems to be related to how MLX builds its computation graph. When each element is expressed as a computation, MLX can properly track the dependencies and vectorize the operations. However, when using direct indexing, it fails to maintain the proper dimensionality.
***

**Comment by angeloskath** [comment]
Hm that is an interesting one.

Let's analyze what happens in the first case which hopefully will make it clear why the 2nd case works.

The function creates an array by using some elements from the input and some zeros. Since the list has mlx arrays, we resort to casting all elements to mlx arrays and stacking them (ie prepending a dimension and concatenating along that dimension).

However, the 0s do not depend on any input which means that they are not vmapped. Currently our concatenate vmap just uses them as is which feels like a bug (which I will make sure it is and fix shortly). As a result it tries to concatenate `0` with the expanded `s[0]` and fails.

In the second case the `0.0` is multiplied with `s[0]` which results in the same shape and the concatenation works as expected.

As a side comment regardless of the bug that should be fixed the get scale function would be way more readable as either of the following:

```python
def get_scale_1(s):
    return mx.diag(s)

def get_scale_2(s):
    return s * mx.eye(len(s))
```

**Comment by feitreim** [comment]
Thanks! I will be changing into the s * mx.eye(3) as that is just much better. But thanks for fixing this.
