### ISSUE TITLE
Safetensor support

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx#182]
Currently only numpy file format is supported, was wondering if safetensor support was of interest.

**Comment by awni** [comment]
I think it could be nice to support this format. The saving/loading code would need to be part of `mx.core` and work with the C++ API.

- It's nice that it supports bf16 as numpy doesn't so we could save and load bf16 through that.
- It seems like a lot of HF models are moving to this format, so it would be convenient to not need to convert to numpy format to get into MLX.

**Comment by dc-dc-dc** [comment]
Agreed, its very straightforward as well. Will start working on this, will probably break down the feature into two prs between loading/saving.

**Comment by osanseviero** [comment]
Hi there :wave: please let us know if there are any questions regarding safetensors and we're happy to lend a hand :hugs:

**Comment by dc-dc-dc** [comment]
Hey @osanseviero, thanks for reaching out and offering support!

I was wondering what the use cases for `__metadata__` object are. I see that there is a `format` property in some example files I downloaded from hf. Should we populate this field as well with something like "mlx" and are there any other fields that should be included?

**Comment by Narsil** [comment]
`__metadata__` is purely informational `str:str` mapping. It's meant as adding information to the file if needed.

It does contain `format: "pt"/"tf"/"flax"` in `transformers` since we load all models from a single format and TF/PT do the convolution order different and same for a few ops.
This format key helps transformers keep track of what layout was the model saved in, and resolve the correct model in during load. To be perfectly honest, there's an overwhelming majority of PT layout models, so you can safely assume so when loading models.

I've seen other platforms also use `__metadata__` to add some kind of checksum for the weights themselves.
The convert tool also keeps track of duplicate tensors which are destroyed during save (As they are redundant).

Happy to help ! 

Also if you're interested we have written some C bindings which could help a tiny bit manipulation (also it will avoid making you pull a JSON library). https://github.com/huggingface/safetensors/pull/259

**Comment by awni** [comment]
@Narsil could you say a bit more about the `safe_load` function and if it does anything noteworthy?

Right now our API is looking like:

```
mx.save_safetensors(file, dict_of_arrays) # may change to **dict_of_arrays 
dict_of_arrays = mx.load(file)
```

**Comment by awni** [comment]
> Also if you're interested we have written some C bindings which could help a tiny bit manipulation (also it will avoid making you pull a JSON library). huggingface/safetensors#259

Just so I understand this comment, is the suggestion that we use your bindings? Could you say what do you do for JSON under the hood? We're trying to keep third-party deps in MLX C++ extremely light-weight (header only) so maybe that would be tricky, not sure.

**Comment by Narsil** [comment]
> @Narsil could you say a bit more about the `safe_load` function and if it does anything noteworthy?
> 
> Right now our API is looking like:
> 
> ```
> mx.save_safetensors(file, dict_of_arrays) # may change to **dict_of_arrays 
> dict_of_arrays = mx.load(file)
> ```
> 

Safe_open is useful over loading all the tensors because you can do lazy loading.

https://huggingface.co/docs/safetensors/index

For instance we use it to do faster loading when doing tensor parallel inference (you can load only the slices required on each shard)

**Comment by Narsil** [comment]
> > Also if you're interested we have written some C bindings which could help a tiny bit manipulation (also it will avoid making you pull a JSON library). huggingface/safetensors#259
> 
> Just so I understand this comment, is the suggestion that we use your bindings? Could you say what do you do for JSON under the hood? We're trying to keep third-party deps in MLX C++ extremely light-weight (header only) so maybe that would be tricky, not sure.

Oh fair enough. Then using you own code is really easy. Safetensors only requires json basically.
