### ISSUE TITLE
FileReader close?

### ISSUE THREAD

**Issue by dougdew64** [ml-explore/mlx#201]
There doesn't seem to be a close member function for FileReader. How do we close instances of FileReader?

**Comment by jagrit06** [comment]
The class `FileReader` does not take ownership of the passed C++ `std::ifstream` - it is passed as a shared pointer and the user has control of when to close it. 

If a `file_path` is passed instead, we construct a shared pointer around a new `std::ifstream` and the expectation is that it is closed automatically upon destruction since only the`FileReader` has a reference to it (https://cplusplus.com/reference/fstream/ifstream/close/)

**Comment by dougdew64** [comment]
Thanks @jagrit06. I should have read the code more closely and answered that question for myself. Next time I'll pay closer attention.
