### ISSUE TITLE
Unable to generate stubs

### ISSUE THREAD

**Issue by douglasdew** [ml-explore/mlx#372]
When attempting to generate stubs per the instructions in https://ml-explore.github.io/mlx/build/html/install.html# I receive an error:

![image](https://github.com/ml-explore/mlx/assets/79527906/fda85694-61b1-4235-9cde-077fe96a50a1)

I'm using the MacOS python installation, and am using a python venv.

**Comment by douglasdew** [comment]
According to the comment in setup.py, it seems that `cpp_function` should be replaced by `typing.Callable`:

![image](https://github.com/ml-explore/mlx/assets/79527906/52256bfa-1af5-47a3-a8d3-631c69241128)

**Comment by douglasdew** [comment]
cpp_function seems to have been replaced by typing.Callable in the generated __init__.pyi file: 

![image](https://github.com/ml-explore/mlx/assets/79527906/98a0f295-bda6-4395-ac41-cb472427bd7d)

And, I'm able to run tests.

All of that suggests that stubs have been successfully generated.

So, it's not clear to me why my attempt to perform the optional stub generation step fails.

**Comment by dc-dc-dc** [comment]
Yeah, this was a small hack I wrote to get around `pybind11-stubgen` failing when it encountered `cpp_function`. It's not ideal, and I don't like the idea of suppressing the error/warning from stubgen as we can miss some stuff. But it looks like it did run to completion since you got the .pyi files and it was able to sed. 

Ideally we should either find a better solution to handle `cpp_function` so that `pybind11-stubgen` doesn't throw that error, or suppress the error for `cpp_function`

**Comment by douglasdew** [comment]
Thank you very much for your workaround and for your explanation @dc-dc-dc .
