### ISSUE TITLE
Kernel failed while performing array matmul operation

### ISSUE THREAD

**Issue by kjdeveloper8** [ml-explore/mlx#376]
There's an issue i am facing while performing matmul operation on array, it causes kernel to restart everytime

#### code
```
a = mx.array([12])
b = mx.array([4])
mx.matmul(a, b)
```

#### error message
<img width="1124" alt="error" src="https://github.com/ml-explore/mlx/assets/46292689/8e89331a-7ee7-450b-927f-3a72b67deeb7">

#### here's system info
```
System: Darwin
Node Name: MacBook-Air.local
Release: 22.4.0
Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
Machine: arm64
Processor: arm
```

python: 3.11.4

**Comment by awni** [comment]
What version of MLX are you using? Building from source, if so what commit? I have to admit I've never seen anything even close to that message you are showing. So you'll need to give us quite a bit more detail on what you are doing before we can be helpful.

**Comment by angeloskath** [comment]
The error is that the two arrays are integers and we are only allowing floating point matmuls. However, this should be caught in the op-level instead of going to the backend such that the exception would surface to the user.

@kjdeveloper8 you should use `mx.array([12.0])` or `mx.array([12]).astype(mx.float32)` to have floating point arrays until this is fixed.

@awni the kernel here refers to the IPython or Jupyter kernel.

**Comment by awni** [comment]
@awni the kernel here refers to the IPython or Jupyter kernel

Makes a lot more sense, thanks!
