### ISSUE TITLE
[BUG] with metal API validation turned on Gather::eval_gpu causes aborts when trying to allocate 0 sized buffer

### ISSUE THREAD

**Issue by davidkoski** [ml-explore/mlx#410]
**Describe the bug**

With metal API validation turned on (`METAL_DEVICE_WRAPPER_TYPE=1 METAL_DEBUG_ERROR_MODE=0`) if you call `Gather::eval_gpu()` for an array that has a zero dimension input you will get an assertion failure and abort:

```
-[MTLDebugDevice newBufferWithLength:options:]:646: failed assertion `Buffer Validation
Cannot create buffer of zero length.
```

Specifically these lines:

```
  // Allocate and fill buffers for shapes and strides
  int idx_ndim = nidx ? inputs[1].ndim() : 0;
  auto idx_shapes_buf = allocator::malloc_or_wait(sizeof(int) * idx_ndim);
  auto idx_strides_buf = allocator::malloc_or_wait(sizeof(size_t) * idx_ndim);
```

`inputs[1]` might be a 0 dimension scalar array (e.g. `mx.array(1)`) in which case `ndim()` is 0 (and honestly the `: 0` default looks a little iffy as it will cause the same trouble).  Anyway, the call to `allocator::malloc_or_wait()` with a size of 0 triggers the abort when metal API validation is turned on.

**To Reproduce**

```python
import mlx.core as mx

arr = mx.array([2, 4, 6, 8]).reshape((2, 2))
x = mx.take(arr, mx.array(1), 0)
print(x)
```

run as:

```
METAL_DEVICE_WRAPPER_TYPE=1 METAL_DEBUG_ERROR_MODE=0 python test.py
```

**Expected behavior**

This should not abort().

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1]
 - Commit hash: `753867123d36c13b29637c648068fd83844b0498`

**Comment by awni** [comment]
After looking for a while:

- Fixing the allocator to skip for size 0 still fails validation due to sending null buffers to kernels
- Using a minimum size still fails validation due to dispatching 0 threads (evidently not allowed either)
- This means we really hav no choice but to avoid 0-sized kernel launches
- If we do that we can use nill buffers because they should never be arguments to kernels.
- The only exception is for gather which makes a 0 sized buffer to store the shapes and strides when using a 0 dim index. The fix there is probably to special case 0 dim indexing ops
