### ISSUE TITLE
[BUG] 'mx. round 'returned different values on CPU and GPU

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#439]
**Describe the bug**
I accidentally set the decimals parameter of mx.round very large, I noticed that all the returns were 'nan', I think this is caused by exceeding the representation range of float32, so I want to test the maximum decimals value that can generate valid values. 

I found that for my test array a = mx.array([-2.5, -1.5, -0.5, 0.5, 1.5, 2.5]), when decimals is set to 39, both the CPU and GPU return nan. When  decimals is set to 38, 'mx. round 'returned different values on CPU and GPU, I guess this may be due to the different mathematical libraries used by the CPU and GPU, I suggest you can solve this problem, in practical applications, especially when it comes to high-precision floating-point operations, this hardware difference needs to be taken into account.

By the way, in the official documentation of mlx, I noticed that in the Python API Reference, under the Array column, there are two 'mlx.core.array.dtype'.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
#original array
a = mx.array([-2.5, -1.5, -0.5, 0.5, 1.5, 2.5])
print(a)

#gpu
b = mx.round(a,decimals=38)
print(mx.default_device(),b)

#cpu
mx.set_default_device(mx.cpu)
c = mx.round(a,decimals=38)
print(mx.default_device(),c)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/7cde6170-cba8-46d4-868d-642744f571aa)

**Expected behavior**
I think the same result should be returned.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.7.0

**Comment by angeloskath** [comment]
Hmm I understand your frustration but I don't think there is anything to do about that... Unfortunately it seems the gpu handles this edge case a bit differently than the cpu and we are way too close to the edge of the precision of the dtype.

For example, PyTorch returns 0 for `1e-38` on the mps device.

Simply put we will always return the wrong answer for >=38 decimal places, the compromise is what kind of wrong answer do we want. For instance we could throw when >37 decimal places but then we would need something else for float16 etc.

Just to be clear, there isn't a framework out there that returns the correct answer for all decimals (for float32 obviously the range is much bigger for float64 or other custom types). The question is whether we error out at 37 or 38 or 39.

Let me know if you think we should address this edge case somehow, otherwise I will close the issue.

**Comment by Redmept1on** [comment]
Thank you for your reply. I will close the issue.
