### ISSUE TITLE
[Feature] Support SafeTensor and GGUF format in loading and saving model weights.

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx#486]
MLX now supports loading and saving npz, safeTensor, and gguf formats, but in the module's `load_weights` and `save_weights` methods we still save the weights as npz format. This has already caused some confusion within the community, for example in the mlx-example issue [here](https://github.com/ml-explore/mlx-examples/issues/314). I'm just wondering if there are any plans to support safeTensor and gguf formats in these methods?

**Comment by awni** [comment]
Yea we can definitely do that, it's a minor modification!

**Comment by awni** [comment]
Also, I will probably start with safetensors only until our API for gguf solidifies.

**Comment by mzbac** [comment]
I was thinking of implementing it in C++ because we need to check the file header to determine the file type. However, if you prefer doing it in Python, I am happy to work on that :).

**Comment by awni** [comment]
We should do the saving part in PyThon for now because we aren't planning to add a new C++ API to `mlx.core` to save any format.

So this function ` Module.save_weights(self, file: str)` should check the extension and dispatch accordingly.

I believe the `Module.load_weights` function should already work with `safetensors` since `mlx.core.load` does actually check the extension and dispatch accordingly.

**Comment by awni** [comment]
@mzbac if you are interested to work on it, LMK I will assign this issue to you! Happy to have the contribution.

**Comment by mzbac** [comment]
> @mzbac if you are interested to work on it, LMK I will assign this issue to you! Happy to have the contribution.

Yeah, I am more than happy to take care of this issue :)
