### ISSUE TITLE
[Feature] `mx.diag`

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx#503]
Follow the [NumPy API](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

- C++ op with bindings in python
- tests

**Comment by ManishAradwad** [comment]
I'll start working on this!

**Comment by ManishAradwad** [comment]
@awni i added the `diag` function to ops.cpp and called it in `array.cpp`. I'm testing it after building but getting `AttributeError: module 'mlx.core' has no attribute 'diag'`

am I missing something?

**Comment by Rifur13** [comment]
Make sure to add a python binding under "python/src/ops.cpp".

**Comment by PRESIDENT810** [comment]
Hi @ManishAradwad, I was also working on this last week (see #526) and I've got it mostly working with C++ & Python tests. Maybe you can use that as a reference if you have any questions about how to implement this.

There's still one big problem for me... I don't know how to implement Diagonal operator's vip() for autograd. I think we might need a complement operator of diagonal() like fill_diagonal() to make the reverse mode autograd work. I checked numpy's implementation but that only supports 2D array. I also checked JAX's implementation but they seem to be implementing this in Python level with JIT, instead of a C++ operator. I also tried to check PyTorch's implementation but that codebase is kinda messy, and I haven't found where they implement diagonal operator's gradient.

I'm getting stuck here. Any suggestions about how to implement this Diagonal's vjp API?
