### ISSUE TITLE
mlx.core.flatten lacks dimension check

### ISSUE THREAD

**Issue by Redmept1on** [ml-explore/mlx#557]
**Describe the bug**
When I tried to use the mlx.core.flatten operation on two-dimensional arrays, there was no crash when I set end_axis to more than 2.

**To Reproduce**

Include code snippet
```python
import mlx.core as mx

# Create an array for flattening
array_a = mx.array([[1, 2], [3, 4]])

flattened = mx.flatten(array_a, start_axis=0, end_axis=6)
print(flattened)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/06fc43fe-69d0-408f-8a6f-95b1d29428dc)

In addition, there is another problem, which I think is error message. The default start_axis is 0 and end_axis is -1. When I try to set start_axis to 2, the following error occurs, I think there is a problem with this error message. Because the default value start_axis is less than end_axis.

```python
import mlx.core as mx

# Create an array for flattening
array_a = mx.array([[1, 2], [3, 4]])

flattened = mx.flatten(array_a, start_axis=2, end_axis=-1)
print(flattened)
```
![image](https://github.com/ml-explore/mlx/assets/84373897/54f75223-f4f9-4d30-98cc-620fe77a23c7)

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version 0.10.0

**Comment by awni** [comment]
- We clamp the axis to the beginning and end so if `end_axis` is really large we will clip it. That's intentional, not a bug. I don't know if it's a desirable feature or not, but I will leave it that way for now unless we have a good reason to change it.
- In the second case a -1 axis is treated as `1` so that is why you see that message.

I will update the docs to be more clear to help with this.

**Comment by Redmept1on** [comment]
Thanks for explaining！
