### ISSUE TITLE
Can I add a Chinese translation to the document

### ISSUE THREAD

**Issue by xuehangcang** [ml-explore/mlx#617]
Can I add a Chinese translation to the document，I want more Chinese users to know about xlx.

[https://github.com/ml-explore/mlx/tree/main/docs](https://github.com/ml-explore/mlx/tree/main/docs)

**Comment by awni** [comment]
I think it is a nice idea to have translations, but I'm not sure where the best place for them is...

**Comment by hwhsu1231** [comment]
Hello @XuehangCang,

I’ve started the [mlx-docs-l10n](https://github.com/localizethedocs/mlx-docs-l10n) project to centralize the translation efforts for the MLX Documentation. Since you've shown interest in this area, I’d love to invite you to join us and contribute to the Simplified Chinese translation. Your help would be greatly appreciated!

**Comment by XuehangCang** [comment]
ok
________________________________
发件人: Haowei Hsu ***@***.***>
发送时间: 2026年2月1日 19:42
收件人: ml-explore/mlx ***@***.***>
抄送: XuehangCang ***@***.***>; Mention ***@***.***>
主题: Re: [ml-explore/mlx] Can I add a Chinese translation to the document (Issue #617)

[https://avatars.githubusercontent.com/u/71438617?s=20&v=4]hwhsu1231 left a comment (ml-explore/mlx#617)<https://github.com/ml-explore/mlx/issues/617#issuecomment-3830994330>

Hello @XuehangCang<https://github.com/XuehangCang>,

I’ve started the mlx-docs-l10n<https://github.com/localizethedocs/mlx-docs-l10n> project to centralize the translation efforts for the MLX Documentation. Since you've shown interest in this area, I’d love to invite you to join us and contribute to the Simplified Chinese translation. Your help would be greatly appreciated!

―
