### ISSUE TITLE
Macbook (M1 pro 16Gb) nearly freeze/unresponsive when running inference

### ISSUE THREAD

**Issue by nxphi47** [ml-explore/mlx#840]
Hi, I got my mlx and mlx-lm “properly” setup and running seemingly normally on my macbook (installed with pypip on native arm environment). I’m running inference a quantized mistral-7b model. 

However, when the model performs an inference, virtually the whole mac nearly freeze unresponsive, lags and I could not use any other functions (like browsing webs). It only goes back to normal when the model finishes the generation. 

Is this normal and expected, or something wrong with the setup, installation?

**Comment by mzbac** [comment]
It looks like insufficient memory is causing the swapping on your laptop, but I believe the recent version has improved a lot in terms of memory efficiency. Would you try the latest versions of mlx-lm and mlx?

**Comment by nxphi47** [comment]
Thanks @mzbac I update to the latest version but it seems to be same still :(

**Comment by mzbac** [comment]
If it's a memory issue, you may need to try using the smaller model like `mlx-community/phi-2-hf-4bit-mlx`.

**Comment by angeloskath** [comment]
@nxphi47 I think there might be some other issue because I can run Mistral 7B quantized at 4 bits easily on an 8GB M1 (no pro :-) ) at 11 tokens per second. This means it should take quite a bit less than 8GB of memory so some slowdown may be possible but freezing of the Mac should be unlikely. Do you have other big operations happening?

On my M2 air (admittedly with 24GB of memory) I can easily run inference and be on a video call or watch YouTube videos at the same time.

**Comment by nxphi47** [comment]
@angeloskath Thanks for the info. The mistral I used is also 4-bit quantized, so it shouldn't take up all the RAM. And I feel running with llama.cpp is smoother than MLX. :(

**Comment by angeloskath** [comment]
Yeah exactly, it doesn't take up all the memory, so it is probably something to do with your config or usage. Feel free to provide more details for us to either help you fix the config/install or reproduce the issue if one is there.
