### ISSUE TITLE
[BUG] mapping confusion when in_axes is a negative index  in `vmap`

### ISSUE THREAD

**Issue by 0x1orz** [ml-explore/mlx#922]
**Describe the bug**
in_axes' mapping confusion when in_axes is a negative index  in `vmap`

**To Reproduce**

Include code snippet
```python
import mlx 
import mlx.nn as nn
input_size=5
hidden_size=12
x = mx.random.normal((2, 25, 12))
hidden_layer = nn.Sequential(nn.Linear(input_dims=hidden_size, output_dims=hidden_size, bias=True), nn.Tanh())
all_h = []
for idx in range(x.shape[-2]):
    h = hidden_layer(x[...,idx,:])
    all_h.append(h)
all_h = mx.stack(all_h, -2)

vmap_pos_h = mx.vmap(hidden_layer, in_axes=1, out_axes=1)(x)
mx.allclose(all_h, vmap_pos_h)                              # array(True, dtype=bool)
```
that is all right, 
while 
```python
vmap_neg_h = mx.vmap(hidden_layer, in_axes=-2, out_axes=-2)(x)    # [vmap] Axis -2 invalid for input with 3 dimensions.
mx.allclose(all_h, vmap_neg_h) 
```
but 
```python
vmap_neg_h = mx.vmap(hidden_layer, in_axes=-1, out_axes=-2)(x)    
mx.allclose(all_h, vmap_neg_h)                            # array(True, dtype=bool)
```

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.4
 - Version: mlx=0.8.1

**Comment by angeloskath** [comment]
Yes indeed, negative axes are not supported by vmap. This mostly stems from the fact that we use `-1` internally to denote "no vectorization". In the python side we use `None` so we could easily fix that in the python side. The problem then is that the C++ API and the Python one would behave differently.

I am not too sure we want that. The way forward is one of the following
- Allow negative axes only in python
- Fix the C++ side by accepting a `std::optional<int>` for the axis instead of having -1 as a special value
- Disallow negative axes everywhere but throw a proper error letting people know instead of returning wrong results

The 1st and 3rd bullet are quite easy small changes. I think the best one is the 2nd though. @awni and @jagrit06 wdyt?

Either way @0x1orz thanks for making that issue, this is definitely a bad behavior on the MLX side that we should fix promptly.

**Comment by awni** [comment]
If we went with `std::optional<int>` how does that look in C++? Just the API and still use `-1` in the primitives `vmap`? Do we change all the vmaps to input and return `std::vector<std::optional<int>>`? 

The latter seems like a big change for a small benefit on the C++ side. So maybe the former is better? Then we do the remapping on just the input / output vector out side the primitives.

I would prefer that or option 1 (just allowing negative axes only in Python with `None` to denote no axis).
