### ISSUE TITLE
[BUG] array indexing produces Cannot reshape array of size 3 into shape (1,1)

### ISSUE THREAD

**Issue by davidkoski** [ml-explore/mlx#937]
**Describe the bug**
`a[i, ..., ::2, :] = 1` fails to assign: Cannot reshape array of size 3 into shape (1,1)

both the get operation and numpy equivalent work as expected

**To Reproduce**

```python
>>> i = mx.array([2, 1])
>>> a = mx.arange(540).reshape(3, 3, 4, 5, 3)
>>> a[i, ..., ::2, :] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: [reshape] Cannot reshape array of size 3 into shape (1,1).
```

**Expected behavior**

I expect (and numpy agrees) that it should mutate `a`

**Desktop (please complete the following information):**
 - commit hash f30b659291b1d279034c77891a2c700e50d7a6f3

**Comment by davidkoski** [comment]
If I am understanding the code right, I think it is something like this:

- `a[i, ..., ::2, :] = 1` turns into `a[i, :, :, ::2, :] = 1`
- num_slices = 4
- num_simple_slices_post = 3
- num_strided_slices = 1
- idx_ndim = 2

So that all looks fine.  The first problem is that I think the logic for handling the strides slice is incorrect:

```python
      // If it's a simple slice, we only need to add the start index
      if (array_num >= num_arrays && num_strided_slices <= 0 && stride == 1) {
...
      }
      // Otherwise we expand the slice into indices using arange
      else {
        auto idx = arange(start, end, stride, uint32);
        auto loc = slice_num + (arrays_first ? max_dim : 0);
        idx_shape[loc] = idx.size();
...
        slice_num++;
        num_strided_slices--;
```

The first slice we encounter at index 1 (`:`) enters the strided case because `num_strided_slices == 1` but I think this should be treated as a "simple slice".  Anyway, it goes through the else case where `num_strided_slices` is decremented.  I don't know that this is directly harmful, but it doesn't seem to match the intent.

The next `:` goes through the simple slice case.

The third slice, `::2`, ends up in the else case, but `slice_num` (which is really maybe `strided_slice_num`?) is already 1, `max_dim` is 1 and thus `loc` is `2`.  `idx_shape` is `(1, 1)` and surprisingly `idx_shape[2] = 3` neither mutates or throws an error, but `idx_shape` is incorrectly left as `(1, 1)`.

I suspect that the error is that the first slice incorrectly goes through the strided case even though it is not strided, which makes the accounting for the handling of strides invalid.

**Comment by davidkoski** [comment]
Simply removing the `num_strided_slices` from the condition makes it behave identically to numpy in this case and _seems_ to be the right logic, but I have no idea what else that might affect:

```python
      if (array_num >= num_arrays && num_strided_slices <= 0 && stride == 1) {

-> 

      if (array_num >= num_arrays && stride == 1) {
```

**Comment by awni** [comment]
Thanks for diving into that @davidkoski one of us will take a look and confirm the fix. CC @jagrit06 as well who has the most context on that. 

Our indexing code is very brittle as it turns out.. partly due to numpy having some unexpected edge case behavior and partly due to us trying to optimize where we can :\.

**Comment by davidkoski** [comment]
On the plus side my port to swift faithfully carried this bug, but in swift the array index aborts the program :-)

**Comment by jagrit06** [comment]
@davidkoski The issue with removing the check for `num_strided_slices` is that our updates may then require transposes thanks to how `scatter` works 
For example, with an array `a` of shape `(3, 4, 4, 5, 3)` and `a[mx.array([2, 1]), :, :, ::2, :]` shape being `(2, 4, 4, 3, 3)`, 
We would then expand the strided axis 3 and get `a[mx.array([2, 1]), :, :, mx.array([0, 2, 4]), :]`
if we do not expand the `:` at axis 1 and 2, then the required update shape would `(2, 3) + (1, 4, 4, 1, 3)` - but the shape of `a[mx.array([2, 1]), :, :, ::2, :]` is `(2, 4, 4, 3, 3)`
So that's why we choose to expand those axes as well, leading to an update of shape `(2, 4, 4, 3) +  (1, 1, 1, 1, 3)`

**Comment by jagrit06** [comment]
This issue was a simple miscalculation happening with the counting of the simply strided axes at the end that can be packed in the scatter, will send a PR momentarily

**Comment by davidkoski** [comment]
Awesome -- I will apply the same fix to the swift code when you are done.
